# yaml-language-server: $schema=../../../schemas/formula-v1.json
apiVersion: hub.openeverest.io/v1
kind: Extension

metadata:
  name: percona-server-mongodb
  type: provider
  displayName: "MongoDB (Percona)"
  icon: ./mongodb_icon.png
  description: |
    Production-ready MongoDB clusters powered by the Percona Operator.
    Supports replica sets and sharded topologies.
  categories:
    - database
    - mongodb
  keywords:
    - nosql
    - document-store
    - percona
  homepage: https://github.com/openeverest/provider-percona-server-mongodb
  sourceRepo: https://github.com/openeverest/provider-percona-server-mongodb
  license: Apache-2.0
  maturity: alpha
  maintainers:
    - name: "OpenEverest Team"
      email: "cncf-openeverest-maintainers@lists.cncf.io"
      github: "openeverest"

spec:
  provider:
    providerName: percona-server-mongodb
    supportedEngines:
      - mongodb

  compatibility:
    openeverest: ">=2.0.0"

  capabilities:
    ha: true
    backups: true
    pitr: true
    restores: true
    monitoring: true
    sharding: true
    mongodb.versions: ["6", "7", "8"]

  artifacts:
    chart:
      defaultChannel: stable
      channels:
        stable:
          ref: oci://ghcr.io/openeverest/charts/provider-percona-server-mongodb
          version: "0.7.2"

  install:
    helm:
      releaseName: provider-percona-server-mongodb
      namespace: everest-system
